-- AlterTable
ALTER TABLE `UserTransactionStatus` MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'CANCELED', 'USER_PAYMENT_PENDING', 'WAITING_CHECK_EVIDENCE', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'RECEIVED_ADDRESS', 'SENDING_BOOK', 'SEND_BOOK_COMPLETED', 'WAITING_RECEIVED_BOOK', 'RECEIVED_BOOK') NOT NULL DEFAULT 'PENDING';
