CREATE TABLE userProfilePictures (
  pictureId INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  pictureUrl VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN DEFAULT FALSE,
  deleted BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (userId) REFERENCES users(userId)
);

