import { BookCard } from "../models/Books";

export const mockBookData: BookCard[] = [
  {
    bookId: 1,
    title: "Brave New World",
    author: "Aldous Huxley",
    genreId: 2,
    condition: "Used",
    description: "A dystopian novel set in a futuristic World State.",
    ownerId: 1,
    status: "PUBLIC",
    bookImageId: 1,
    views: 123,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 2,
    title: "1984",
    author: "George Orwell",
    genreId: 2,
    condition: "New",
    description:
      "A novel about a totalitarian regime that uses surveillance and control to maintain power.",
    ownerId: 2,
    status: "PUBLIC",
    bookImageId: 2,
    views: 89,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 3,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genreId: 1,
    condition: "Used",
    description: "A novel about racial injustice in the American South.",
    ownerId: 3,
    status: "PUBLIC",
    bookImageId: 3,
    views: 150,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 4,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genreId: 1,
    condition: "Used",
    description:
      "A novel about the American dream and the excesses of the Jazz Age.",
    ownerId: 4,
    status: "PUBLIC",
    bookImageId: 4,
    views: 101,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 5,
    title: "Moby Dick",
    author: "Herman Melville",
    genreId: 3,
    condition: "New",
    description:
      "A novel about a captain's obsessive quest to hunt a giant white whale.",
    ownerId: 5,
    status: "PUBLIC",
    bookImageId: 5,
    views: 78,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 6,
    title: "War and Peace",
    author: "Leo Tolstoy",
    genreId: 3,
    condition: "Used",
    description:
      "A novel about the French invasion of Russia and its impact on Tsarist society.",
    ownerId: 6,
    status: "PUBLIC",
    bookImageId: 6,
    views: 112,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 7,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genreId: 4,
    condition: "Used",
    description:
      "A romantic novel about the manners and matrimonial machinations of British society.",
    ownerId: 7,
    status: "PUBLIC",
    bookImageId: 7,
    views: 134,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 8,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genreId: 1,
    condition: "New",
    description:
      "A novel about teenage rebellion and the alienation of modern youth.",
    ownerId: 8,
    status: "PUBLIC",
    bookImageId: 8,
    views: 98,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 9,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genreId: 5,
    condition: "New",
    description:
      "An epic fantasy novel about the battle between good and evil in Middle-earth.",
    ownerId: 9,
    status: "PUBLIC",
    bookImageId: 9,
    views: 256,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 10,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genreId: 5,
    condition: "Used",
    description:
      "A fantasy novel about the adventures of Bilbo Baggins in Middle-earth.",
    ownerId: 10,
    status: "PUBLIC",
    bookImageId: 10,
    views: 145,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 11,
    title: "The Odyssey",
    author: "Homer",
    genreId: 3,
    condition: "Used",
    description:
      "An epic poem about the Greek hero Odysseus's journey home after the Trojan War.",
    ownerId: 11,
    status: "PUBLIC",
    bookImageId: 11,
    views: 98,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 12,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    genreId: 4,
    condition: "New",
    description:
      "A novel about the life and struggles of an orphaned girl who becomes a governess.",
    ownerId: 12,
    status: "PUBLIC",
    bookImageId: 12,
    views: 153,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 13,
    title: "The Iliad",
    author: "Homer",
    genreId: 3,
    condition: "Used",
    description:
      "An epic poem about the Trojan War and the battles between Achilles and Hector.",
    ownerId: 13,
    status: "PUBLIC",
    bookImageId: 13,
    views: 102,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 14,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    genreId: 3,
    condition: "New",
    description:
      "A novel about the moral struggles and psychological conflicts of three brothers.",
    ownerId: 14,
    status: "PUBLIC",
    bookImageId: 14,
    views: 165,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 15,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genreId: 3,
    condition: "Used",
    description:
      "A novel about the mental anguish and moral dilemmas of a young man who commits a murder.",
    ownerId: 15,
    status: "PUBLIC",
    bookImageId: 15,
    views: 134,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 16,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    genreId: 4,
    condition: "New",
    description:
      "A novel about the tragic romance and social pressures faced by a Russian aristocrat.",
    ownerId: 16,
    status: "PUBLIC",
    bookImageId: 16,
    views: 145,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 17,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    genreId: 3,
    condition: "Used",
    description:
      "An epic poem about the journey through Hell, Purgatory, and Paradise.",
    ownerId: 17,
    status: "PUBLIC",
    bookImageId: 17,
    views: 177,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 18,
    title: "Ulysses",
    author: "James Joyce",
    genreId: 3,
    condition: "New",
    description:
      "A modernist novel about the experiences of Leopold Bloom in Dublin on June 16, 1904.",
    ownerId: 18,
    status: "PUBLIC",
    bookImageId: 18,
    views: 190,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 19,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    genreId: 6,
    condition: "Used",
    description:
      "A novel that chronicles the rise and fall of the Buendía family in the fictional town of Macondo.",
    ownerId: 19,
    status: "PUBLIC",
    bookImageId: 19,
    views: 158,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
  {
    bookId: 20,
    title: "The Grapes of Wrath",
    author: "John Steinbeck",
    genreId: 1,
    condition: "New",
    description:
      "A novel about the struggles of a poor family of tenant farmers during the Great Depression.",
    ownerId: 20,
    status: "PUBLIC",
    bookImageId: 20,
    views: 137,
    bookView: 0,
    createdAt: undefined,
    updatedAt: undefined,
  },
];
